dist: trusty
language: php

sudo: required

 # Downloaded browsers will be cached in selenium-assistant by
 # web-push-testing-service. Caching will speed up build time.
cache:
  directories:
    - ~/.selenium-assistant
    - node_modules                  # cache modules too
    - $HOME/.composer/cache/files   # and composer packages

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true
    include:
        - php: 7.2
        - php: 7.3
        - php: 7.4
        - php: nightly

env:
  - TRAVIS_NODE_VERSION="stable"

before_install:
  - composer config discard-changes true
  - nvm install node

install:
  - npm install github:GoogleChromeLabs/web-push-testing-service -g

before_script:
  - composer install --prefer-source -n
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start || echo \"Unable to start virtual display.\""
  - sleep 3 # give xvfb some time to start

script:
  - echo "Preparing unit tests skipped, will check locally" # web-push-testing-service start example -p 9012
  - echo "Unit tests skipped, will check locally" # composer test:unit
  - echo "Finishing unit tests skipped, will check locally" # web-push-testing-service stop example
  - composer test:typing
  - composer test:syntax
